### ISSUE TITLE
Unzip command is not found

### ISSUE THREAD

**Issue by tjcreedy** [johnne/coidb#16]
Just testing out coidb based on your comment [here](https://github.com/nf-core/ampliseq/issues/427). I'm running on an HPC within a job scheduler and have set up a conda environment containing just the coidb package. Running coidb I get an error in the `extract_zipfile` process, `/usr/bin/bash: line 1: unzip: command not found`. Since this is a pretty bare bones HPC, this common package isn't installed and on the PATH by default!

Adding the `conda-forge` `unzip` package to my conda environment solves the issue. Perhaps this needs to be included as a dependency for coidb?

**Comment by johnne** [comment]
Thanks for testing and finding that missing package! WIll look into it right away and make a change for the next release.

**Comment by johnne** [comment]
Fixed with #17
